services:
  nuxt-app:
    container_name: nuxt-app
    build:
      context: ./nuxt-app
    volumes:
      - ./nuxt-app/app:/app
    tty: true
    # command: yarn dev
    ports:
      - "3001:3001"
    networks:
      - app-network

  express-api:
    container_name: express-api
    build:
      context: ./express-api
    volumes:
      - ./express-api/app:/app
    tty: true
    # command: yarn dev
    ports:
      - "3002:3002"
      - "9229:9229"
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d/

    # depends_on:
    #   - nuxt-app
    #   - express-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
