name: "share-mediaplayer"
services:
  nuxt-app:
    container_name: nuxt-app
    environment:
      - NODE_ENV="production"
    build:
      context: ./nuxt-app
      dockerfile: ./nuxt-app/docker/dockerfile.production
    restart: unless-stopped
    volumes:
      - ./nuxt-app:/app
      - app-build-volume:/app/.output
      - app-deps:/app/node_modules

    tty: true

    ports:
      - "3001:3001"
    networks:
      - app-network

  express-api:
    container_name: express-api
    environment:
      - NODE_ENV="production"
    build:
      context: ./express-api
      dockerfile: ./express-api/docker/dockerfile.production
    restart: unless-stopped
    volumes:
      - ./express-api:/api
      - api-build-volume:/api/dist
      - api-deps:/api/node_modules

    tty: true

    ports:
      - "3002:3002"
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d/

    depends_on:
      - nuxt-app
      - express-api
    networks:
      - app-network
volumes:
  api-deps:
  api-build-volume:
  app-deps:
  app-build-volume:

networks:
  app-network:
    name: "app-network"
    driver: bridge
