name: "share-mediaplayer"
services:
  nuxt-app:
    container_name: nuxt-app
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: ./nuxt-app
    restart: unless-stopped
    volumes:
      - ./nuxt-app/app:/app
      - app-build-volume:/app/.output
      - app-deps:/app/node_modules

    tty: true
    # command: yarn start
    # command: yarn dev
    ports:
      - "3001:3001"
    networks:
      - app-network

  express-api:
    container_name: express-api
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: ./express-api
    restart: unless-stopped
    volumes:
      - ./express-api/api:/api
      - api-build-volume:/api/dist
      - api-deps:/api/node_modules

    tty: true
    # command: yarn start
    # command: yarn dev
    ports:
      - "3002:3002"
      - "9229:9229"
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d/

    # depends_on:
    #   - nuxt-app
    #   - express-api
    networks:
      - app-network
volumes:
  api-deps:
  api-build-volume:
  app-deps:
  app-build-volume:

networks:
  app-network:
    name: "app-network"
    driver: bridge
