FROM node:20.18-alpine

# RUN apt-get update 
# RUN apt-get install -y ffmpeg tini bash
# RUN apt-get install -y htop
# RUN rm -rf /var/lib/apt/lists/*

RUN apk update && apk add --no-cache ffmpeg tini bash htop
# SHELL ["/bin/bash", "-c"]
ENV NODE_ENV='development'


WORKDIR /api
VOLUME '/api'

COPY ./api/ ./
RUN yarn global add pm2
RUN yarn install

EXPOSE 3002
# CMD ["yarn","dev"]

# ENTRYPOINT ["/sbin/tini", "--"]
# CMD ["bash"]

