# Dockerfile
FROM nginx:latest

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY configs /etc/nginx/conf.d/

# COPY entrypoint.sh /entrypoint.sh

# Make the entrypoint script executable
# RUN chmod +x /entrypoint.sh

# Set the entrypoint
# ENTRYPOINT ["/entrypoint.sh"]
